### ISSUE TITLE
danger-kotlin-jira 404

### ISSUE THREAD

**Issue by Sboti03** [danger/awesome-danger#38]
[https://github.com/rojanthomas/danger-kotlin-jira](https://github.com/rojanthomas/danger-kotlin-jira) is not found :(

**Comment by Sboti03** [comment]
Does this exist or has it not been implemented?

**Comment by manicmaniac** [comment]
I think it was deleted from GitHub.
At least, it existed at some point.
https://central.sonatype.com/artifact/com.rojanthomas/danger-kotlin-jira
